name: Cache Demo

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: prime-cache-d10a2cd
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-d10a2cd

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Populate cache if missed
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/demo
          echo "primed" > ~/.cache/demo/data.txt